#21 Improved Trainee Documentation
atlp-rwanda/atlp-pulse-mobile pull request #113
Opened 2024-11-15 08:43 UTC by munezeromicha

### What does this PR do?

This PR introduces trainee documentation to help new users understand how to get started with the app and navigate the login process. The documentation includes the following sections:

- **Getting Started:** Provides an overview of the Devpulse platform, highlighting the semi-open nature of access and the invitation-based signup process.
- **Terminology to be Familiar With:** Defines key terms and concepts, such as Organizations, Programs, Managers, and Trainees.
- **Signing Up as a User:** Outlines the process of joining the platform via an invite from an organization admin.
- **Signing in as a User:** Details the steps to log into the app by selecting an organization and providing credentials.
- **How to Login to an Organization:** Walks through the login steps, from selecting an organization to verifying credentials and accessing the platform.

### How should this be manually tested?

- Navigate to the trainee documentation section in the app.
- Verify that the **Getting Started**, **Signing in your organization**, **Signing in as a User**, and they are clearly displayed and formatted.
- Check that the descriptions and steps are clear and align with the app's actual login and signup flow.
- Ensure all terminology definitions, login instructions, and signup process steps are accurate and easy to follow for trainees.

### ScreenShots:

<div style="display: flex; flex-wrap: wrap;">
    <img src="https://github.com/user-attachments/assets/2b627d55-4433-408c-84d7-bdd063524639" alt="Screenshot 1" height="480px">
    <img src="https://github.com/user-attachments/assets/c5864a67-1a23-44a4-b895-f096729fe9ee" alt="Screenshot 1" height="480px">
    <img src="https://github.com/user-attachments/assets/d784a10b-7f76-43ec-9452-ec5a1e38827a" alt="Screenshot 2" height="480px">
    <img src="https://github.com/user-attachments/assets/99f89b9f-372b-4f1c-a70c-6a54f3fc802a" alt="Screenshot 1" height="480px">
    <img src="https://github.com/user-attachments/assets/c0ad1edc-03f6-4311-a482-3f12244049cc" alt="Screenshot 1" height="480px">
    <img src="https://github.com/user-attachments/assets/f9c97bbc-01c9-462c-92c8-3ebc3ecbbb20" alt="Screenshot 2" height="480px">
</div>

2024-11-15 09:42 UTC, MugemaneBertin2001 requested changes
Nice job @munezeromicha  just find a way to localize it

2024-11-21 07:18 UTC, fredshema requested changes

2024-11-21 07:18 UTC, fredshema commented on components/sidebar.tsx
> +      path: '/dashboard/trainee/documentation',
This route is for help, you should change the `t('navbar.docs')` route.

2024-11-21 07:30 UTC, fredshema approved these changes

2024-11-21 09:03 UTC, pacifiquemboni approved these changes

2024-11-21 12:02 UTC, closed without merging