Tickets page implementation
atlp-rwanda/atlp-pulse-mobile pull request #116
Opened 2024-11-18 12:00 UTC by Mbabazi12

### What does this PR do?
This PR is for implementing Tickets page

### Description of Task to be completed
The task was all about designing the tickets page and displaying them if any.

### How This should be tested?
- To test this task after cloning the project on your end, checkout my branch `ft-tickets-page`, and then run the project
- After that go on the sidebar on the tickets page and see if you have any tickets available.
- If you have tickets you can scroll on the pagination and filter to show how many you want || go to page that you want.

### Screenshots

![Ticket(Dark)](https://github.com/user-attachments/assets/6bb8dcb6-0329-4012-ae15-94cfd3e0b045)
![Ticket(Light)](https://github.com/user-attachments/assets/64aa2c4c-dab1-4d03-8416-065f92325ba8)
![TicketDetails(Dark)](https://github.com/user-attachments/assets/57bc8fdf-caef-4ca4-ad9f-3d3eb8a47b26)
![TicketDetails](https://github.com/user-attachments/assets/e99c2c23-858b-4cfa-8ea2-25e417e0e7f1)

2024-11-19 06:18 UTC, Christian-Ishimwe approved these changes

2024-11-20 10:39 UTC, MugemaneBertin2001 approved these changes

2024-11-20 11:27 UTC, pacifiquemboni requested changes

2024-11-20 11:27 UTC, pacifiquemboni commented on internationalization/locales/kin.json
> +  "tickets": {
@Mbabazi12 check on this translations, they should be translated in kinyarwanda yet they are in french

2024-11-20 11:27 UTC, pacifiquemboni commented on app/dashboard/trainee/tickets.tsx
> +      console.log("fetched token:", token)
this console should be removed

2024-11-20 14:15 UTC, niyibi250 approved these changes

2024-11-20 15:03 UTC, ncutixavier approved these changes

2024-11-20 15:03 UTC, merged