Fix Preference Page Icons
atlp-rwanda/atlp-pulse-mobile pull request #120
Opened 2024-11-19 13:03 UTC by niyibi250

### What does this PR do?
This PR updates the trainee preference settings page to maintain consistency by replacing all buttons or clickables with Chevron icons.
### Description of Task to be completed?

- Replace the forward arrow icons on the settings page with Chevron icons for better UI consistency.
- Ensure that the new Chevron icons are interactive and reflect the current colorScheme (light or dark mode).
- Update the push notification section to include expand/collapse functionality, toggling between a downward and forward Chevron icon.

### How should this be manually tested?

1. Navigate to the trainee preference settings page.

2. Verify that all forward arrows have been replaced by Chevron icons.

3. Test the push notification section:

- Click the Chevron icon to expand the section and reveal the switch.
- Click the Chevron icon again to collapse the section.

4. Ensure the Chevron icons adjust their color dynamically based on the active colorScheme.

### Any background context you want to provide?
N/A
### What are the relevant pivotal tracker/Trello stories?
N/A
### Screenshots

![image](https://github.com/user-attachments/assets/b1f31e64-f29b-49ef-abd1-e8f287d0f5dd)

![image](https://github.com/user-attachments/assets/4a27533a-396c-48aa-b80a-f290a9a29188)

2024-11-20 08:12 UTC, MugemaneBertin2001 requested changes
![Screenshot 2024-11-20 100951](https://github.com/user-attachments/assets/a2e84d71-4705-4937-828e-ad7948492982)
1. Use standard react native icons framework instead of images in assets
2. Check settings we have on web as that are written
3. Change to toggle on privacy and login history just as that are on web

2024-11-20 11:26 UTC, MugemaneBertin2001 requested changes
![Screenshot 2024-11-20 132505](https://github.com/user-attachments/assets/5516c512-0b04-42c7-8202-064178cafc03)
@niyibi250  check on these toggler on web

2024-11-20 19:11 UTC, pacifiquemboni commented on assets/Preference_icons/down_arrow.png
Good work @niyibi250 
but i think iti is not advisable to use static files especially icons

2024-11-20 19:11 UTC, pacifiquemboni reviewed
Good work @niyibi250 
but i think iti is not advisable to use static files especially icons

2024-11-20 19:12 UTC, pacifiquemboni reviewed
Resolve conflicting files

2024-11-24 23:23 UTC, MugemaneBertin2001 requested changes

2024-11-24 23:23 UTC, MugemaneBertin2001 commented on app/auth/login/index.tsx
> +      console.log(userInput)
remove these console logs

2024-11-24 23:23 UTC, MugemaneBertin2001 commented on app/auth/two-factor/index.tsx
> +    console.log('typeeeee')
This is also needs to be removed

2024-11-24 23:23 UTC, MugemaneBertin2001 commented on assets/Preference_icons/down_arrow.png
Try to use this one https://reactnativeelements.com/docs/customization/themeprovider

2024-11-25 09:04 UTC, Christian-Ishimwe requested changes

2024-11-25 09:04 UTC, Christian-Ishimwe commented on %ProgramData%/Microsoft/Windows/UUS/State/_active.uusver
delete this file

2024-11-26 14:40 UTC, fredshema requested changes

2024-11-26 14:40 UTC, fredshema commented on %ProgramData%/Microsoft/Windows/UUS/State/_active.uusver
This file is not needed

2024-11-26 14:40 UTC, fredshema commented
Also fix conflicts

2024-11-26 15:27 UTC, fredshema requested changes
Make sure to also run format before pushing

2024-11-26 15:27 UTC, fredshema commented on app/auth/two-factor/index.tsx
> +
Can these be moved to their own mutation files

2024-11-27 09:13 UTC, MugemaneBertin2001 approved these changes
This looks Good to me

2024-11-27 10:20 UTC, fredshema approved these changes

2024-11-27 10:28 UTC, merged