ch(#13): Setup unit testing circle ci and coveralls badges
atlp-rwanda/atlp-pulse-mobile pull request #25
Opened 2024-08-29 06:02 UTC by munezeromicha

**Description**

This pull request introduces the following setup to improve our project's code quality and continuous integration process:

**Unit Testing Setup:**

- Unit test Implemented is Jest.
- Configured the testing environment to run tests consistently across different environments.

**CircleCI Integration:**

- Set up CircleCI for continuous integration.
- Configured CircleCI to run the unit tests on every commit and pull request.
- Ensured the build pipeline is stable and reliable.

**Coveralls Integration:**

- Integrated Coveralls to track code coverage.
- Added the Coveralls badge to the README file to display the current coverage status.
- Configured the project to automatically upload coverage reports to Coveralls after each build.

2024-08-30 08:55 UTC, ncutixavier commented
- Your test failed, how can I merge the setup test when tests are failing
- This PR is not ready

2024-08-30 08:58 UTC, munezeromicha commented
*Yes! am working on it!*



On Fri, 30 Aug 2024 at 10:55, Ncuti Xavier ***@***.***> wrote:

>
>    - Your test failed, how can I merge the setup test when tests are
>    failing
>    - This PR is not ready
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/atlp-rwanda/atlp-pulse-mobile/pull/25#issuecomment-2320546552>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A6FPKLDLXIWYOOVDGKOGNPDZUAXRVAVCNFSM6AAAAABNJVL5B6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGMRQGU2DMNJVGI>
> .
> You are receiving this because you were assigned.Message ID:
> ***@***.***>
>

2024-09-02 09:56 UTC, fredshema approved these changes

2024-09-02 14:07 UTC, Salim-54 approved these changes

2024-09-03 09:13 UTC, fredshema requested changes

2024-09-03 09:13 UTC, fredshema commented on tailwind.config.js
This needs to be in `jest.config.js` not `tailwind.config.js`

2024-09-03 09:13 UTC, fredshema commented on package.json
> +        "coverage": "nyc npm test && nyc report --reporter=text-lcov | coveralls"
Specify one command to generate coverage reports

2024-09-03 09:13 UTC, fredshema commented on app/+html.tsx
Remove this file for web, we will not need a web version for the app

2024-09-03 14:11 UTC, fredshema approved these changes

2024-09-03 14:19 UTC, ncutixavier approved these changes

2024-09-03 14:20 UTC, merged