Ch(#19) Setup app theme
atlp-rwanda/atlp-pulse-mobile pull request #27
Opened 2024-09-02 07:27 UTC by aimeudoxie

### Setup app theme

## What this PR do

This pull request sets up the theme of the app by adding font colors in both light and dark mode , font style and the necessary components  to the app configurations 

## Task completed

- [ ] colors: Primary, secondary, action, success, warning, danger and neutral
- [ ] Font style : inter
- [ ] components: buttons

2024-09-02 13:13 UTC, munezeromicha approved these changes

2024-09-02 14:05 UTC, fredshema approved these changes

2024-09-03 09:19 UTC, fredshema requested changes

2024-09-03 09:19 UTC, fredshema commented on components/buttons.tsx
> +  size?: "S" | "L";
Use conventional sizing, i.e: `sm, md, lg, xl`

2024-09-03 09:19 UTC, fredshema commented on components/buttons.tsx
> +  state?: "default" | "pressed" | "outlined" | "Hover" | "Disabled";
Use consistent style, either use states that have the first letter as capitalized or make them all lowercase

2024-09-03 11:22 UTC, fredshema approved these changes

2024-09-03 13:56 UTC, munezeromicha approved these changes
Good job!

2024-09-05 11:54 UTC, ncutixavier approved these changes

2024-09-05 11:54 UTC, ncutixavier commented on tailwind.config.js
> +      danger:{
Use error instead of danger

2024-09-05 11:54 UTC, merged