Dashboard layout & sidebar
atlp-rwanda/atlp-pulse-mobile pull request #41
Opened 2024-09-27 09:58 UTC by Mbabazi12

### What does this PR do
This PR is for the dashboard layout design and the sidebar design.

### Description of Task to be completed
The task was about to design the dashboard layout of the trainee app and also design the sidebar contents.

### How This should be tested?
You have to run the app and register your account or if you already have account you can login and once it's successfully you can see the dashboard layout and when you click on the menu bar you can see the sidebar.

### Screenshots
![Dasboard-layout](https://github.com/user-attachments/assets/e4c7ff34-e72e-4d53-b07f-2d2175b07b17)
![Sidebar](https://github.com/user-attachments/assets/886a8f84-a74d-4fa3-8673-56b3e9c61fa1)

2024-10-01 08:19 UTC, pacifiquemboni approved these changes

2024-10-01 08:27 UTC, pacifiquemboni commented on __tests__/components/sidebar.test.tsx
> +    expect(getByText('Notifications')).toBeTruthy();
On the web version, we decided to remove the Notifications link from the sidebar because it's already available on the top navbar.

2024-10-01 08:42 UTC, fredshema commented
@Mbabazi12 check the sidebar in dark mode, it doesn't change to light mode.

2024-10-01 09:26 UTC, MugemaneBertin2001 requested changes
@ncutixavier  asked for design our drawer to be 100% of width

2024-10-01 11:53 UTC, Mbabazi12 commented
@fredshema @pacifiquemboni worked on the changes you requested, you can review again

2024-10-01 11:57 UTC, fredshema approved these changes

2024-10-01 12:11 UTC, Mbabazi12 commented
@MugemaneBertin2001 Actually according to the figma design we are using from @Christian-Ishimwe you can see that the sidebar is not full on width

2024-10-01 13:11 UTC, pacifiquemboni reviewed
![Trainee sidebar- light](https://github.com/user-attachments/assets/15f9d5ec-7306-4542-b099-de767fa8ef8c)
## Theme is missing
check on the bottom of this image

2024-10-01 13:25 UTC, MugemaneBertin2001 approved these changes

2024-10-01 14:13 UTC, Mbabazi12 commented
@pacifiquemboni the theme changes according to your phones current state

2024-10-02 08:22 UTC, ncutixavier approved these changes

2024-10-02 08:22 UTC, merged