$43 Implement sprint rating & Recent feedback
atlp-rwanda/atlp-pulse-mobile pull request #49
Opened 2024-10-03 18:44 UTC by pacifiquemboni

PR Description
This PR Implement sprint rating & Recent feedback

Description of tasks that were expected to be completed
As a trainee, I should be able to see sprint ratings & Recent feedback. 
How has this been tested?
Clone repo
Checkout branch `ft-sprint-ratings`
Make sure that you set the environment variables referring to .env.example
Run` npm install`, then `npm run dev` to check if the app is running successfully

![WhatsApp Image 2024-10-03 at 20 42 26_555cb815](https://github.com/user-attachments/assets/eaca3406-aeae-4af2-9614-65e777e89a28)

2024-10-07 10:15 UTC, fredshema requested changes

2024-10-07 10:15 UTC, fredshema commented on assets/images/arrow-left.png
Please use `Ionicons` for icons, we don't use file icons

2024-10-07 10:22 UTC, fredshema commented
@pacifiquemboni check on figma on the design, your designs doesn't match that

2024-10-07 15:31 UTC, niyibi250 requested changes
check conflict and resolve them

2024-10-08 08:35 UTC, Mbabazi12 commented
@pacifiquemboni this can't be changed into dark mode

2024-10-08 09:31 UTC, pacifiquemboni commented
> @pacifiquemboni this can't be changed into dark mode

check again @Mbabazi12

2024-10-08 10:00 UTC, Mbabazi12 commented
> > @pacifiquemboni this can't be changed into dark mode
> 
> check again @Mbabazi12

Oky i checked and it looks good on my side but could you add the dark mode screenshot for everyone to see it. thank you

2024-10-08 12:16 UTC, Mbabazi12 approved these changes

2024-10-08 13:08 UTC, niyibi250 approved these changes
look good

2024-10-08 14:33 UTC, ncutixavier commented
@pacifiquemboni  there is right padding that need to be checked

2024-10-08 14:59 UTC, pacifiquemboni commented
> @pacifiquemboni there is right padding that need to be checked
worked on it @ncutixavier

2024-10-09 09:04 UTC, fredshema approved these changes

2024-10-09 12:11 UTC, munezeromicha approved these changes

2024-10-09 14:17 UTC, ncutixavier commented on assets/images/mdi-eye.png
Remove this if it is not being used anywhere

2024-10-09 14:17 UTC, ncutixavier commented on components/sprintratings/index.tsx
> +  const [userToken, setUserToken] = useState<string | null>(null);
Nit sure if we really need these comments!

2024-10-09 14:17 UTC, ncutixavier commented on components/sprintratings/index.tsx
Are you planning to have more files in `sprintratings`?

2024-10-10 09:15 UTC, ncutixavier approved these changes

2024-10-10 09:16 UTC, merged