#10 Account password reset
atlp-rwanda/atlp-pulse-mobile pull request #57
Opened 2024-10-16 10:25 UTC by fredshema

### What does this PR do?

This PR includes designs and implementations of trainee password reset.

### Description of Task to be completed?

If a user wants to change their password, they provide the current password and a pair of new password. If the current password is correct the password is updated otherwise an appropriate error message is thrown.

### How should this be manually tested?

- Open the app and login.
- Click on the profile picture and navigate to account tab
- Fill in the form and logout
- Check if the previous password is working and if the new password is working

### Screenshots

<img width="300" src="https://github.com/user-attachments/assets/e3c0df6b-e9fd-41bb-a4a0-8966bedd8e16" />
<img width="300" src="https://github.com/user-attachments/assets/38d25f58-28e5-4ce8-b155-c2ba3356572e" />

2024-10-21 09:01 UTC, niyibi250 requested changes
please first resolve the confilct

2024-10-22 15:04 UTC, MugemaneBertin2001 approved these changes

2024-10-22 15:28 UTC, Mbabazi12 approved these changes

2024-10-23 06:24 UTC, niyibi250 approved these changes

2024-10-23 13:55 UTC, ncutixavier commented
This has many unnecessary changes, that need to be removed @fredshema

2024-10-23 13:58 UTC, Mbabazi12 commented
Most of those changes are coming from formatting @ncutixavier

2024-10-23 14:50 UTC, ncutixavier approved these changes

2024-10-23 14:50 UTC, merged