Fix Org Field Issues
atlp-rwanda/atlp-pulse-mobile pull request #74
Opened 2024-10-28 09:48 UTC by niyibi250

### What does this PR do?
This PR updates the input field by ensuring that error messages are not displayed before the user starts typing, modifies the placeholder text color, and changes the extension name.

### Description of Task to be completed?

- Ensure there no error messages before the user starts typing
- Change the placeholder text color for improved readability
- Update the extension name from .co to .org

### How should this be manually tested?

- Open the form where the changes were applied.
- Verify that error messages are not shown until the user begins typing.
- Check that the placeholder text color is updated.
- Confirm that the file extension name change has been applied.

### Any background context you want to provide?
This update improves the user experience by removing potential distractions from error messages appearing prematurely, enhancing placeholder text visibility.

### What are the relevant pivotal tracker/Trello stories?
N/A

### Screenshots

![Screenshot 2024-10-28 110539](https://github.com/user-attachments/assets/cc46f5d7-0ac7-42a2-961f-eaa1ae4cfa07)

### Questions:
N/A

2024-10-28 11:13 UTC, MugemaneBertin2001 requested changes
Why does It show errors on password while typing email?
![Screenshot 2024-10-28 131026](https://github.com/user-attachments/assets/020ec0ff-706a-44ca-904a-0ba4e61d48e0)

2024-10-28 12:19 UTC, MugemaneBertin2001 requested changes
Solve this issue as well.
![Screenshot 2024-10-28 131026](https://github.com/user-attachments/assets/b40675f2-f4e2-4096-a794-c2f2b9ef67b5)

2024-10-28 12:50 UTC, fredshema approved these changes

2024-10-28 13:23 UTC, Mbabazi12 commented
@niyibi250 did you change this requests from @MugemaneBertin2001

2024-10-28 21:31 UTC, MugemaneBertin2001 approved these changes

2024-10-30 10:51 UTC, Mbabazi12 approved these changes

2024-10-30 12:31 UTC, ncutixavier approved these changes

2024-10-30 12:34 UTC, merged